# -*- coding: utf-8 -*-
"""Spark DataFrames Project Exercise.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FGwFA09qQpN8kg7vvNcbUJmoP2KPUV2w

# Spark DataFrames Project Exercise

Let's get some quick practice with your new Spark DataFrame skills, you will be asked some basic questions about some stock market data, in this case Walmart Stock from the years 2012-2017. This exercise will just ask a bunch of questions, unlike the future machine learning exercises, which will be a little looser and be in the form of "Consulting Projects", but more on that later!

For now, just answer the questions and complete the tasks below.

#### Use the walmart_stock.csv file to Answer and complete the  tasks below!
"""

!pip install pyspark

import pyspark

"""#### Start a simple Spark Session"""

from pyspark.sql import SparkSession
spark = SparkSession.builder.appName('Project1').getOrCreate()

"""#### Load the Walmart Stock CSV File, have Spark infer the data types."""

df_spark = spark.read.csv('/content/walmart_stock.csv',header=True,inferSchema=True)

"""#### What are the column names?"""

df_spark.columns

"""#### What does the Schema look like?"""

df_spark.printSchema()

"""#### Print out the first 5 columns."""

for row in df_spark.head(5):
  print(row)
  print('\n')

"""#### Use describe() to learn about the DataFrame."""

df_spark.describe().show()

"""## Bonus Question!
#### There are too many decimal places for mean and stddev in the describe() dataframe. Format the numbers to just show up to two decimal places. Pay careful attention to the datatypes that .describe() returns, we didn't cover how to do this exact formatting, but we covered something very similar. [Check this link for a hint](http://spark.apache.org/docs/latest/api/python/pyspark.sql.html#pyspark.sql.Column.cast)

If you get stuck on this, don't worry, just view the solutions.
"""

df_spark.describe().printSchema()

from pyspark.sql.functions import format_number

result =df_spark.describe()

result.select(result['summary'],
              format_number(result['open'].cast('float'),2).alias('open'),
              format_number(result['High'].cast('float'),2).alias('High'),
              format_number(result['Low'].cast('float'),2).alias('Low'),
              format_number(result['Close'].cast('float'),2).alias('Close'),
              result['Volume'].cast('int').alias('Volume')
              ).show()

"""#### Create a new dataframe with a column called HV Ratio that is the ratio of the High Price versus volume of stock traded for a day."""

new_df = df_spark.withColumn("HV Ratio",df_spark['High']/df_spark['Volume'])
new_df.select("HV Ratio").show()

"""#### What day had the Peak High in Price?"""

df_spark.orderBy(df_spark['High'].desc()).head(1)[0][0]

"""#### What is the mean of the Close column?"""

from pyspark.sql.functions import mean
df_spark.select(mean("Close")).show()

"""#### What is the max and min of the Volume column?"""

from pyspark.sql.functions import max,min

df_spark.select(max("Volume"),min("Volume")).show()

"""#### How many days was the Close lower than 60 dollars?"""

df_spark.filter('Close <60').count()

"""#### What percentage of the time was the High greater than 80 dollars ?
#### In other words, (Number of Days High>80)/(Total Days in the dataset)
"""

df_spark.filter('High >80').count() / df_spark.count() *100

"""#### What is the Pearson correlation between High and Volume?
#### [Hint](http://spark.apache.org/docs/latest/api/python/pyspark.sql.html#pyspark.sql.DataFrameStatFunctions.corr)
"""

from pyspark.sql.functions import corr
df_spark.select(corr("HIgh","Volume")).show()

"""#### What is the max High per year?"""

from pyspark.sql.functions import year
year_df = df_spark.withColumn("Year",year(df_spark["Date"]))

year_df.show()

max_df = year_df.groupBy("Year").max()

max_df.show()

max_df.select('Year','max(High)').show()

"""#### What is the average Close for each Calendar Month?
#### In other words, across all the years, what is the average Close price for Jan,Feb, Mar, etc... Your result will have a value for each of these months. 
"""

from pyspark.sql.functions import month

month_df = df_spark.withColumn("Month",month("Date"))

month_avg = month_df.select(['Month','Close']).groupBy('Month').mean()

month_avg.select("Month","avg(Close)").orderBy('Month').show()